name: adele_platform_storage
description: Internal platform-specific ADELE storage root resolution.
publish_to: none
version: 0.1.0

environment:
  sdk: ">=3.10.9 <4.0.0"

resolution: workspace

dependencies:
  path: ^1.9.1

dev_dependencies:
  test: ^1.26.3
