@Timeout(Duration(minutes: 2))
library;

import 'package:path/path.dart' as p;

import 'support/contract_generator_support.dart';

late String _cliSnapshot;

void main() {
  setUpAll(() async {
    final directory = await Directory.systemTemp.createTemp(
      'adele_codegen_cli.',
    );
    addTearDown(() => directory.delete(recursive: true));
    _cliSnapshot = p.join(directory.path, 'contract_codegen.dill');
    final result = await Process.run(Platform.resolvedExecutable, [
      'compile',
      'kernel',
      p.join(
        repositoryRoot().path,
        'packages/contract_codegen/bin/contract_codegen.dart',
      ),
      '-o',
      _cliSnapshot,
    ]);
    expect(result.exitCode, 0, reason: '${result.stdout}\n${result.stderr}');
  });

  for (final (state, contents) in <(String, String?)>[
    ('missing', null),
    ('stale', "part of 'old.dart';\nclass Future<T> {}\n"),
  ]) {
    test('CLI check reports $state output without writing', () async {
      final fixture = await _repositoryFixture();
      final output = File(p.setExtension(fixture.source.path, '.g.dart'));
      if (contents != null) await output.writeAsString(contents);

      await _runCli(fixture.directory, ['--check'], exitCode: 1);
      expect(output.existsSync(), contents != null);
      if (contents != null) expect(await output.readAsString(), contents);
    });

    test(
      'CLI generation repairs $state output and check does not rewrite it',
      () async {
        final fixture = await _repositoryFixture();
        final output = File(p.setExtension(fixture.source.path, '.g.dart'));
        final source = await fixture.source.readAsString();
        if (contents != null) await output.writeAsString(contents);

        await _runCli(fixture.directory, []);
        final generated = await output.readAsString();
        expect(
          generated,
          startsWith(
            '// Generated by ADELE contract_codegen (native transport).\n',
          ),
        );
        await output.setLastModified(DateTime.utc(2000));
        final modified = await output.lastModified();
        await _runCli(fixture.directory, ['--check']);
        expect(await output.lastModified(), modified);
        expect(await output.readAsString(), generated);
        expect(await fixture.source.readAsString(), source);
      },
    );
  }

  test('CLI generation does not rewrite current output', () async {
    final fixture = await _repositoryFixture();
    final generated = await const ContractGenerator().generate(fixture.source);
    await const ContractGenerator().write(generated);
    final output = File(generated.path);
    await output.setLastModified(DateTime.utc(2000));
    final modified = await output.lastModified();

    await _runCli(fixture.directory, []);
    expect(await output.lastModified(), modified);
    expect(await output.readAsString(), generated.contents);
  });

  test('CLI cleans malformed output and recreates a current sibling', () async {
    final fixture = await _repositoryFixture();
    final output = File(p.setExtension(fixture.source.path, '.g.dart'));
    final source = await fixture.source.readAsString();
    await output.writeAsString('legacy or malformed generated output');

    // Cleanup finds configuration from a descendant without resolving source.
    await _runCli(fixture.source.parent, ['--clean']);
    expect(output.existsSync(), isFalse);
    expect(await fixture.source.readAsString(), source);
    await _runCli(fixture.directory, ['--clean']);
    await _runCli(fixture.directory, []);
    expect(output.existsSync(), isTrue);
    await _runCli(fixture.directory, ['--check']);
  });

  test(
    'CLI cleans configured output even when its source is missing',
    () async {
      final fixture = await _repositoryFixture();
      final output = File(p.setExtension(fixture.source.path, '.g.dart'));
      await fixture.source.delete();
      await output.writeAsString('legacy output with a deleted source');

      await _runCli(fixture.directory, ['--clean']);
      expect(output.existsSync(), isFalse);
    },
  );

  test(
    'clean removes only marked canonical orphans in packages/plugins',
    () async {
      final fixture = await _repositoryFixture();
      final generated = await const ContractGenerator().generate(
        fixture.source,
      );
      final orphans = <File>[
        await _write(
          fixture.directory,
          'packages/removed/fixture.g.dart',
          generated.contents,
        ),
        await _write(
          fixture.directory,
          'plugins/removed/fixture.g.dart',
          generated.contents,
        ),
      ];
      final preserved = <File>[
        fixture.source,
        await _write(
          fixture.directory,
          'packages/example/lib/authored.dart',
          '// authored\n',
        ),
        await _write(
          fixture.directory,
          'packages/example/lib/other.g.dart',
          "// GENERATED CODE - DO NOT MODIFY BY HAND.\npart of 'other.dart';\n",
        ),
        await _write(
          fixture.directory,
          'packages/example/lib/unmarked.g.dart',
          "part of 'unmarked.dart';\n",
        ),
        await _write(
          fixture.directory,
          'plugins/mismatch.g.dart',
          generated.contents,
        ),
        await _write(
          fixture.directory,
          'plugins/not_native.dart',
          generated.contents,
        ),
        await _write(
          fixture.directory,
          'app/fixture.g.dart',
          generated.contents,
        ),
        await _write(fixture.directory, 'fixture.g.dart', generated.contents),
        for (final folder in [
          '.dart_tool',
          '.git',
          '.hidden',
          'build',
          'coverage',
        ])
          await _write(
            fixture.directory,
            'packages/example/$folder/nested/fixture.g.dart',
            generated.contents,
          ),
        for (final (index, part) in [
          'other.dart',
          '../fixture.dart',
          './fixture.dart',
          'file:fixture.dart',
          'fixture.dart?query',
          'fixture.dart#fragment',
          'fixture%2Edart',
        ].indexed)
          await _write(
            fixture.directory,
            'plugins/invalid$index/fixture.g.dart',
            generated.contents.replaceFirst(
              "part of 'fixture.dart';",
              "part of '$part';",
            ),
          ),
        await _write(
          fixture.directory,
          'plugins/no_part/fixture.g.dart',
          '${DartContractEmitter.nativeHeader}\nconst authored = 1;\n',
        ),
        await _write(
          fixture.directory,
          'plugins/named_part/fixture.g.dart',
          '${DartContractEmitter.nativeHeader}\npart of fixture;\n',
        ),
        await _write(
          fixture.directory,
          'plugins/comment/fixture.g.dart',
          "${DartContractEmitter.nativeHeader}\n// part of 'fixture.dart';\n",
        ),
        await _write(
          fixture.directory,
          'plugins/string_marker/fixture.g.dart',
          "const text = '''\n${DartContractEmitter.nativeHeader}\npart of 'fixture.dart';\n''';\n",
        ),
      ];
      final before = <String, String>{
        for (final file in preserved) file.path: await file.readAsString(),
      };
      // No configured sources remain: marked orphans are still discoverable.
      await _write(fixture.directory, 'contract_codegen.yaml', 'sources:\n');
      await _runCli(fixture.directory, ['--clean']);
      for (final orphan in orphans) {
        expect(orphan.existsSync(), isFalse, reason: orphan.path);
      }
      for (final file in preserved) {
        expect(await file.readAsString(), before[file.path], reason: file.path);
      }
    },
  );

  test(
    'clean does not follow file, directory, or scan-root symlinks',
    () async {
      final fixture = await _repositoryFixture();
      final generated = await const ContractGenerator().generate(
        fixture.source,
      );
      final outside = await createFixture('authored');
      final target = await _write(
        outside.directory,
        'fixture.g.dart',
        generated.contents,
      );
      final links = <Link>[
        await Link(
          p.setExtension(fixture.source.path, '.g.dart'),
        ).create(target.path),
        await Link(
          p.join(fixture.directory.path, 'packages', 'linked'),
        ).create(outside.directory.path),
        await Link(
          p.join(fixture.directory.path, 'plugins'),
        ).create(outside.directory.path),
      ];
      // A configured output behind a symlink must not bypass traversal policy.
      await _write(fixture.directory, 'contract_codegen.yaml', '''
sources:
  - packages/example/lib/fixture.dart
  - packages/linked/fixture.dart
  - plugins/fixture.dart
''');
      await _runCli(fixture.directory, ['--clean']);
      expect(await target.readAsString(), generated.contents);
      for (final link in links) {
        expect(link.existsSync(), isTrue, reason: link.path);
      }
    },
  );

  test(
    'configured cleanup skips cache trees and never deletes a source',
    () async {
      final fixture = await _repositoryFixture();
      final files = <File>[
        await _write(
          fixture.directory,
          'packages/example/lib/fixture.g.dart',
          'authored configured source',
        ),
        for (final folder in ['.dart_tool', 'build', 'coverage'])
          await _write(
            fixture.directory,
            'packages/example/$folder/fixture.g.dart',
            'cache',
          ),
      ];
      await _write(fixture.directory, 'contract_codegen.yaml', '''
sources:
  - packages/example/lib/fixture.dart
  - packages/example/lib/fixture.g.dart
  - packages/example/.dart_tool/fixture.dart
  - packages/example/build/fixture.dart
  - packages/example/coverage/fixture.dart
''');
      await _runCli(fixture.directory, ['--clean']);
      for (final file in files) {
        expect(file.existsSync(), isTrue, reason: file.path);
      }
    },
  );

  for (final arguments in <List<String>>[
    ['--clean', '--check'],
    ['--clean', '--source', 'fixture.dart'],
    ['--clean', '--source='],
    ['--clean', 'fixture.dart'],
  ]) {
    test(
      'rejects conflicting CLI arguments $arguments before deletion',
      () async {
        final fixture = await _repositoryFixture();
        final output = await _write(
          fixture.directory,
          'packages/example/lib/fixture.g.dart',
          'legacy',
        );
        await _runCli(fixture.directory, arguments, exitCode: 64);
        expect(await output.readAsString(), 'legacy');
      },
    );
  }

  for (final source in [
    '../outside.dart',
    '/outside.dart',
    'packages/not_dart.txt',
  ]) {
    test(
      'validates all configured clean paths before deleting: $source',
      () async {
        final fixture = await _repositoryFixture();
        final output = await _write(
          fixture.directory,
          'packages/example/lib/fixture.g.dart',
          'legacy',
        );
        await _write(fixture.directory, 'contract_codegen.yaml', '''
sources:
  - packages/example/lib/fixture.dart
  - $source
''');
        await _runCli(fixture.directory, ['--clean'], exitCode: 64);
        expect(await output.readAsString(), 'legacy');
      },
    );
  }

  test('check with an explicit source remains supported', () async {
    final fixture = await _repositoryFixture();
    final generated = await const ContractGenerator().generate(fixture.source);
    await const ContractGenerator().write(generated);
    await _write(
      fixture.directory,
      'contract_codegen.yaml',
      'not a sources list',
    );
    await _runCli(fixture.directory, [
      '--check',
      '--source',
      fixture.source.path,
    ]);
  });

  test('clean requires repository configuration', () async {
    final directory = await Directory.systemTemp.createTemp('adele_no_config.');
    addTearDown(() => directory.delete(recursive: true));
    await _runCli(directory, ['--clean'], exitCode: 64);
  });
}

Future<ContractFixture> _repositoryFixture() async {
  final fixture = await createFixture(minimalContract(namedValue: true));
  final source = File(
    p.join(fixture.directory.path, 'packages/example/lib/fixture.dart'),
  );
  await source.parent.create(recursive: true);
  await fixture.source.rename(source.path);
  await _write(
    fixture.directory,
    'contract_codegen.yaml',
    'sources:\n  - packages/example/lib/fixture.dart\n',
  );
  return ContractFixture(fixture.directory, source);
}

Future<File> _write(Directory root, String path, String contents) async {
  final file = File(p.join(root.path, path));
  await file.parent.create(recursive: true);
  await file.writeAsString(contents);
  return file;
}

Future<void> _runCli(
  Directory directory,
  List<String> arguments, {
  int exitCode = 0,
}) async {
  final result = await Process.run(Platform.resolvedExecutable, [
    _cliSnapshot,
    ...arguments,
  ], workingDirectory: directory.path);
  expect(
    result.exitCode,
    exitCode,
    reason: '${result.stdout}\n${result.stderr}',
  );
}
