// GENERATED CODE - DO NOT MODIFY BY HAND.
// Generated by contract_codegen from workspace_demo_contract.dart.

import 'package:adele_contract/adele_contract.dart';
import 'package:adele_plugin_api/adele_plugin_api.dart';
import 'package:workspace_demo_contract/workspace_demo_contract.dart';

final class WorkspaceDemoServiceDispatcher {
  const WorkspaceDemoServiceDispatcher(this._service);

  final WorkspaceDemoService _service;

  Future<Map<String, Object?>> dispatch(Map<Object?, Object?> request) async {
    final Object? requestId = request['requestId'];
    try {
      if (requestId is! int || request['kind'] != 'request') {
        throw const AdeleProtocolException('Malformed request envelope.');
      }
      final Map<Object?, Object?> payload = _generatedMap(
        request['payload'],
        'request payload',
      );
      final Object result = switch (request['method']) {
        'workspaceDemo.listDirectory' => await _service.listDirectory(
          _decodeResourceRef(payload['directory']),
        ),
        'workspaceDemo.readTextFile' => await _service.readTextFile(
          _decodeResourceRef(payload['file']),
        ),
        _ => throw const AdeleRemoteFailure(
          code: 'unknown_method',
          message: 'Unknown workspace demo method.',
        ),
      };
      return <String, Object?>{
        'kind': 'response',
        'requestId': requestId,
        'ok': true,
        'payload': switch (result) {
          final DirectoryListing value => _encodeDirectoryListing(value),
          final TextFileContents value => _encodeTextFileContents(value),
          _ => throw StateError('Unsupported generated result.'),
        },
      };
    } on WorkspaceDemoFailure catch (error) {
      return _failure(requestId, error.code, error.message, error.details);
    } on AdeleRemoteFailure catch (error) {
      return _failure(requestId, error.code, error.message, error.details);
    } on AdeleProtocolException catch (error) {
      return _failure(
        requestId,
        'invalid_request',
        error.message,
        const <String, Object?>{},
      );
    } on Object catch (error, stackTrace) {
      return _failure(
        requestId,
        'internal_error',
        'The backend request failed unexpectedly.',
        <String, Object?>{
          'developmentError': error.toString(),
          'developmentStack': stackTrace.toString(),
        },
      );
    }
  }
}

Map<String, Object?> _failure(
  Object? requestId,
  String code,
  String message,
  Map<String, Object?> details,
) => <String, Object?>{
  'kind': 'response',
  if (requestId is int) 'requestId': requestId,
  'ok': false,
  'error': <String, Object?>{
    'code': code,
    'message': message,
    'details': details,
  },
};

ResourceRef _decodeResourceRef(Object? value) {
  final Map<Object?, Object?> map = _generatedMap(value, 'ResourceRef');
  final Object? uri = map['uri'];
  final Object? mediaType = map['mediaType'];
  if (uri is! String || (mediaType != null && mediaType is! String)) {
    throw const AdeleProtocolException('Malformed ResourceRef.');
  }
  return ResourceRef(uri: Uri.parse(uri), mediaType: mediaType as String?);
}

Map<String, Object?> _encodeResourceRef(ResourceRef value) => <String, Object?>{
  'uri': value.uri.toString(),
  'mediaType': value.mediaType,
};

Map<String, Object?> _encodeDirectoryListing(DirectoryListing value) =>
    <String, Object?>{
      'directory': _encodeResourceRef(value.directory),
      'entries': value.entries
          .map(
            (DirectoryEntry entry) => <String, Object?>{
              'resource': _encodeResourceRef(entry.resource),
              'name': entry.name,
              'kind': entry.kind.name,
            },
          )
          .toList(growable: false),
    };

Map<String, Object?> _encodeTextFileContents(TextFileContents value) =>
    <String, Object?>{
      'resource': _encodeResourceRef(value.resource),
      'text': value.text,
    };

Map<Object?, Object?> _generatedMap(Object? value, String label) {
  if (value is Map<Object?, Object?>) return value;
  if (value is Map) return value.cast<Object?, Object?>();
  throw AdeleProtocolException('Expected a map for $label.');
}
