// GENERATED CODE - DO NOT MODIFY BY HAND.
// Generated by contract_codegen from workspace_demo_contract.dart.

part of 'workspace_demo_contract.dart';

final class WorkspaceDemoServiceClient implements WorkspaceDemoService {
  const WorkspaceDemoServiceClient(this._channel);

  final AdeleRequestChannel _channel;

  @override
  Future<DirectoryListing> listDirectory(ResourceRef directory) async {
    try {
      return _decodeDirectoryListing(
        await _channel.request('workspaceDemo.listDirectory', <String, Object?>{
          'directory': _encodeResourceRef(directory),
        }),
      );
    } on AdeleRemoteFailure catch (error) {
      throw WorkspaceDemoFailure(
        code: error.code,
        message: error.message,
        details: error.details,
      );
    }
  }

  @override
  Future<TextFileContents> readTextFile(ResourceRef file) async {
    try {
      return _decodeTextFileContents(
        await _channel.request('workspaceDemo.readTextFile', <String, Object?>{
          'file': _encodeResourceRef(file),
        }),
      );
    } on AdeleRemoteFailure catch (error) {
      throw WorkspaceDemoFailure(
        code: error.code,
        message: error.message,
        details: error.details,
      );
    }
  }
}

Map<String, Object?> _encodeResourceRef(ResourceRef value) => <String, Object?>{
  'uri': value.uri.toString(),
  'mediaType': value.mediaType,
};

ResourceRef _decodeResourceRef(Object? value) {
  final Map<Object?, Object?> map = _generatedMap(value, 'ResourceRef');
  final Object? uri = map['uri'];
  final Object? mediaType = map['mediaType'];
  if (uri is! String || (mediaType != null && mediaType is! String)) {
    throw const AdeleProtocolException('Malformed ResourceRef.');
  }
  return ResourceRef(uri: Uri.parse(uri), mediaType: mediaType as String?);
}

DirectoryEntry _decodeDirectoryEntry(Object? value) {
  final Map<Object?, Object?> map = _generatedMap(value, 'DirectoryEntry');
  final Object? name = map['name'];
  final Object? kind = map['kind'];
  if (name is! String || kind is! String) {
    throw const AdeleProtocolException('Malformed DirectoryEntry.');
  }
  return DirectoryEntry(
    resource: _decodeResourceRef(map['resource']),
    name: name,
    kind: switch (kind) {
      'directory' => DirectoryEntryKind.directory,
      'file' => DirectoryEntryKind.file,
      _ => throw AdeleProtocolException(
        'Unknown DirectoryEntryKind value: $kind.',
      ),
    },
  );
}

DirectoryListing _decodeDirectoryListing(Object? value) {
  final Map<Object?, Object?> map = _generatedMap(value, 'DirectoryListing');
  final Object? entries = map['entries'];
  if (entries is! List) {
    throw const AdeleProtocolException('Malformed DirectoryListing entries.');
  }
  return DirectoryListing(
    directory: _decodeResourceRef(map['directory']),
    entries: entries.map(_decodeDirectoryEntry).toList(growable: false),
  );
}

TextFileContents _decodeTextFileContents(Object? value) {
  final Map<Object?, Object?> map = _generatedMap(value, 'TextFileContents');
  final Object? text = map['text'];
  if (text is! String) {
    throw const AdeleProtocolException('Malformed TextFileContents.');
  }
  return TextFileContents(
    resource: _decodeResourceRef(map['resource']),
    text: text,
  );
}

Map<Object?, Object?> _generatedMap(Object? value, String label) {
  if (value is Map<Object?, Object?>) return value;
  if (value is Map) return value.cast<Object?, Object?>();
  throw AdeleProtocolException('Expected a map for $label.');
}
