import 'dart:io';

import 'package:test/test.dart';
import 'package:yaml/yaml.dart';

void main() {
  test(
    'configured contract parts are local, ignored, and never tracked',
    () async {
      final config =
          loadYaml(File('contract_codegen.yaml').readAsStringSync()) as YamlMap;
      final sources = (config['sources'] as YamlList).cast<String>();
      expect(sources, isNotEmpty);
      final outputs = <String>[];
      for (final source in sources) {
        expect(source, endsWith('.dart'));
        final output =
            '${source.substring(0, source.length - '.dart'.length)}.g.dart';
        outputs.add(output);
        final basename = output.split('/').last;
        expect(File(source).readAsStringSync(), contains("part '$basename';"));
        expect(
          File(output).existsSync(),
          isTrue,
          reason: 'Bootstrap must create $output',
        );
      }
      final tracked = await Process.run('git', [
        'ls-files',
        '-z',
        '--',
        '*.g.dart',
      ]);
      expect(tracked.exitCode, 0, reason: tracked.stderr.toString());
      final paths = tracked.stdout
          .toString()
          .split('\x00')
          .where((path) => path.isNotEmpty);
      expect(
        paths.where(outputs.contains),
        isEmpty,
        reason:
            'Native contract parts must not be committed, even with git add -f.',
      );
      for (final path in paths) {
        expect(
          File(path).readAsStringSync(),
          isNot(
            contains(
              '// Generated by ADELE contract_codegen (native transport).',
            ),
          ),
          reason: 'Unconfigured ADELE native output must not be tracked: $path',
        );
      }
      final ignored = await Process.run('git', [
        'check-ignore',
        '--no-index',
        '--',
        ...outputs,
      ]);
      expect(ignored.exitCode, 0, reason: ignored.stderr.toString());
      expect(
        ignored.stdout.toString().split('\n').where((path) => path.isNotEmpty),
        unorderedEquals(outputs),
        reason:
            'Add an exact .gitignore entry when configuring a new contract.',
      );
    },
  );
}
